tasks:
- name: SSNP_ODT
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_SSNP_ODT\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\SSNP_ODT\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\SSNP_ODT
- name: confocal-nlos-fk
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_confocal-nlos-fk\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\confocal-nlos-fk\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\confocal-nlos-fk
- name: conventional_ptychography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_conventional_ptychography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\conventional_ptychography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\conventional_ptychography
- name: ct_dual_energy
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_ct_dual_energy\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\ct_dual_energy\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\ct_dual_energy
- name: ct_fan_beam
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_ct_fan_beam\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\ct_fan_beam\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\ct_fan_beam
- name: ct_poisson_lowdose
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_ct_poisson_lowdose\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\ct_poisson_lowdose\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\ct_poisson_lowdose
- name: ct_sparse_view
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_ct_sparse_view\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\ct_sparse_view\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\ct_sparse_view
- name: differentiable_deflectometry
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_differentiable_deflectometry\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\differentiable_deflectometry\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\differentiable_deflectometry
- name: diffusion_mri_dti
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_diffusion_mri_dti\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\diffusion_mri_dti\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\diffusion_mri_dti
- name: eht_black_hole_dynamic
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_dynamic\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_dynamic\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_dynamic
- name: eht_black_hole_feature_extraction_dynamic
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_feature_extraction_dynamic\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_feature_extraction_dynamic\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_feature_extraction_dynamic
- name: eht_black_hole_original
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_original\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_original\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_original
- name: eht_black_hole_tomography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_tomography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_tomography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_tomography
- name: eht_black_hole_UQ
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_UQ\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_UQ\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_UQ
- name: eit_conductivity_reconstruction
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eit_conductivity_reconstruction\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eit_conductivity_reconstruction\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eit_conductivity_reconstruction
- name: electron_ptychography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_electron_ptychography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\electron_ptychography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\electron_ptychography
- name: exoplanet_imaging
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_exoplanet_imaging\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\exoplanet_imaging\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\exoplanet_imaging
- name: fourier_ptychography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_fourier_ptychography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\fourier_ptychography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\fourier_ptychography
- name: fpm_inr_reconstruction
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_fpm_inr_reconstruction\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\fpm_inr_reconstruction\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\fpm_inr_reconstruction
- name: hessian_sim
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_hessian_sim\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\hessian_sim\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\hessian_sim
- name: insar_phase_unwrapping
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_insar_phase_unwrapping\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\insar_phase_unwrapping\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\insar_phase_unwrapping
- name: lensless_imaging
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_lensless_imaging\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\lensless_imaging\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\lensless_imaging
- name: light_field_microscope
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_light_field_microscope\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\light_field_microscope\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\light_field_microscope
- name: lucky_imaging
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_lucky_imaging\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\lucky_imaging\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\lucky_imaging
- name: mcr_hyperspectral
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mcr_hyperspectral\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mcr_hyperspectral\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mcr_hyperspectral
- name: microscope_denoising
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_microscope_denoising\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\microscope_denoising\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\microscope_denoising
- name: mri_dynamic_dce
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_dynamic_dce\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_dynamic_dce\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_dynamic_dce
- name: mri_grappa
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_grappa\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_grappa\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_grappa
- name: mri_l1_wavelet
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_l1_wavelet\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_l1_wavelet\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_l1_wavelet
- name: mri_noncartesian_cs
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_noncartesian_cs\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_noncartesian_cs\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_noncartesian_cs
- name: mri_pnp_admm
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_pnp_admm\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_pnp_admm\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_pnp_admm
- name: mri_sense
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_sense\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_sense\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_sense
- name: mri_t2_mapping
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_t2_mapping\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_t2_mapping\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_t2_mapping
- name: mri_tv
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_tv\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_tv\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_tv
- name: mri_varnet
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_mri_varnet\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\mri_varnet\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\mri_varnet
- name: pet_mlem
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_pet_mlem\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\pet_mlem\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\pet_mlem
- name: photoacoustic_tomography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_photoacoustic_tomography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\photoacoustic_tomography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\photoacoustic_tomography
- name: plane_wave_ultrasound
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_plane_wave_ultrasound\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\plane_wave_ultrasound\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\plane_wave_ultrasound
- name: pnp_mri_reconstruction
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_pnp_mri_reconstruction\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\pnp_mri_reconstruction\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\pnp_mri_reconstruction
- name: raman_cell_phenotyping
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_raman_cell_phenotyping\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\raman_cell_phenotyping\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\raman_cell_phenotyping
- name: reflection_ODT
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_reflection_ODT\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\reflection_ODT\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\reflection_ODT
- name: seismic_FWI_original
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_seismic_FWI_original\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\seismic_FWI_original\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\seismic_FWI_original
- name: shapelet_source_reconstruction
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_shapelet_source_reconstruction\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\shapelet_source_reconstruction\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\shapelet_source_reconstruction
- name: single_molecule_light_field
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_single_molecule_light_field\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\single_molecule_light_field\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\single_molecule_light_field
- name: spectral_snapshot_compressive_imaging
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_spectral_snapshot_compressive_imaging\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\spectral_snapshot_compressive_imaging\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\spectral_snapshot_compressive_imaging
- name: ultrasound_sos_tomography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_ultrasound_sos_tomography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\ultrasound_sos_tomography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\ultrasound_sos_tomography
- name: usct_FWI
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_usct_FWI\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\usct_FWI\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\usct_FWI
- name: weather_radar_data_assimilation
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_weather_radar_data_assimilation\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\weather_radar_data_assimilation\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\weather_radar_data_assimilation
- name: xray_laminography_tike
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_xray_laminography_tike\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\xray_laminography_tike\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\xray_laminography_tike
- name: xray_ptychography_tike
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_xray_ptychography_tike\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\xray_ptychography_tike\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\xray_ptychography_tike
- name: xray_tooth_gridrec
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_xray_tooth_gridrec\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\xray_tooth_gridrec\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\xray_tooth_gridrec
