tasks:
- name: SSNP_ODT
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_SSNP_ODT\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\SSNP_ODT\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\SSNP_ODT
- name: confocal-nlos-fk
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_confocal-nlos-fk\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\confocal-nlos-fk\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\confocal-nlos-fk
- name: conventional_ptychography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_conventional_ptychography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\conventional_ptychography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\conventional_ptychography
- name: eht_black_hole_UQ
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_UQ\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_UQ\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_UQ
- name: eht_black_hole_dynamic
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_dynamic\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_dynamic\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_dynamic
- name: eht_black_hole_feature_extraction_dynamic
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_feature_extraction_dynamic\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_feature_extraction_dynamic\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_feature_extraction_dynamic
- name: eht_black_hole_original
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_original\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_original\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_original
- name: eht_black_hole_tomography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_eht_black_hole_tomography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_tomography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\eht_black_hole_tomography
- name: fourier_ptychography
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_fourier_ptychography\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\fourier_ptychography\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\fourier_ptychography
- name: hessian_sim
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_hessian_sim\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\hessian_sim\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\hessian_sim
- name: insar_phase_unwrapping
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_insar_phase_unwrapping\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\insar_phase_unwrapping\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\insar_phase_unwrapping
- name: lensless_imaging
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_lensless_imaging\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\lensless_imaging\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\lensless_imaging
- name: light_field_microscope
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_light_field_microscope\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\light_field_microscope\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\light_field_microscope
- name: lucky_imaging
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_lucky_imaging\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\lucky_imaging\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\lucky_imaging
- name: microscope_denoising
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_microscope_denoising\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\microscope_denoising\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\microscope_denoising
- name: plane_wave_ultrasound
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_plane_wave_ultrasound\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\plane_wave_ultrasound\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\plane_wave_ultrasound
- name: reflection_ODT
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_reflection_ODT\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\reflection_ODT\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\reflection_ODT
- name: seismic_FWI_original
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_seismic_FWI_original\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\seismic_FWI_original\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\seismic_FWI_original
- name: single_molecule_light_field
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_single_molecule_light_field\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\single_molecule_light_field\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\single_molecule_light_field
- name: spectral_snapshot_compressive_imaging
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_spectral_snapshot_compressive_imaging\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\spectral_snapshot_compressive_imaging\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\spectral_snapshot_compressive_imaging
