tasks:
- name: lucky_imaging
  python_path: D:\yan1\agent\agent_pipeline\test_conda_envs\task_lucky_imaging\python.exe
  task_description_path: D:\yan1\agent\agent_pipeline\data\tasks\lucky_imaging\README.md
  task_dir: D:\yan1\agent\agent_pipeline\data\tasks\lucky_imaging
