tasks:
 - gt_code_path: /data/yjh/AMICO-master_sandbox/amico_code.py
   name: AMICO-master
   python_path: /usr/local/anaconda3/bin/python
 - gt_code_path: /data/yjh/carspy-main_sandbox/carspy_code.py
   name: carspy-main
   python_path: /home/yjh/.conda/envs/carspy_env/bin/python
 - gt_code_path: /data/yjh/caustics-main_sandbox/caustics_code.py
   name: caustics-main
   python_path: /data/yjh/caustics_env/bin/python
 - gt_code_path: /data/yjh/CT-and-MR-Perfusion-Tool-main_sandbox/ct_mr_perfusion_code.py
   name: CT-and-MR-Perfusion-Tool-main
   python_path: /home/yjh/.conda/envs/pypet_custom/bin/python
 - gt_code_path: /data/yjh/DiffuserCam-Tutorial-master_sandbox/diffuser_cam_code.py
   name: DiffuserCam-Tutorial-master
   python_path: /data/yjh/diffusercam_env/bin/python
 - gt_code_path: /data/yjh/dmipy-master_sandbox/dmipy_code.py
   name: dmipy-master
   python_path: /home/yjh/.conda/envs/patato/bin/python
 - gt_code_path: /data/yjh/hcipy-master/hcipy_standalone.py
   name: hcipy-master
   python_path: /data/yjh/hcipy_env/bin/python
 - gt_code_path: /data/yjh/mne-master_sandbox/mne_code.py
   name: mne-master
   python_path: /data/yjh/mne_env/bin/python
 - gt_code_path: /data/yjh/MPIRF-master_sandbox/mpirf_code.py
   name: MPIRF-master
   python_path: /data/yjh/mpirf_env/bin/python
 - gt_code_path: /data/yjh/MRE-elast-master_sandbox/mre_elast_code.py
   name: MRE-elast-master
   python_path: /data/yjh/us-beamform-linarray-master/myenv/bin/python
 - gt_code_path: /data/yjh/mrf-reconstruction-mlmir2020-master_sandbox/mrf_code.py
   name: mrf-reconstruction-mlmir2020-master
   python_path: /usr/local/anaconda3/bin/python
 - gt_code_path: /data/yjh/mripy-master_sandbox/mripy_code.py
   name: mripy-master
   python_path: /usr/local/anaconda3/bin/python
 - gt_code_path: /data/yjh/oct-cbort-main_sandbox/oct_cbort_code.py
   name: oct-cbort-main
   python_path: /usr/local/anaconda3/bin/python
 - gt_code_path: /data/yjh/phasorpy-main_sandbox/phasorpy_code.py
   name: phasorpy-main
   python_path: /home/yjh/.conda/envs/phasorpy_env/bin/python
 - gt_code_path: /data/yjh/PtyLab-main/ptylab_standalone.py
   name: PtyLab-main
   python_path: /data/yjh/ptylab_env/bin/python
 - gt_code_path: /data/yjh/PyAbel-master_sandbox/pyabel_code.py
   name: PyAbel-master
   python_path: /data/yjh/pyabel_env/bin/python
 - gt_code_path: /data/yjh/pyDHM-master_sandbox/pydhm_code.py
   name: pyDHM-master
   python_path: /data/yjh/pydhm_env/bin/python
 - gt_code_path: /data/yjh/PyHoloscope-main_sandbox/pyholoscope_code.py
   name: PyHoloscope-main
   python_path: /data/yjh/pyholoscope_new_env/bin/python
 - gt_code_path: /data/yjh/PySMLFM-main_sandbox/pysmlfm_code.py
   name: PySMLFM-main
   python_path: /data/yjh/pysmlfm_env/bin/python
 - gt_code_path: /data/yjh/spectral_ct_examples-master_sandbox/spectral_ct_code.py
   name: spectral_ct_examples-master
   python_path: /home/yjh/.conda/envs/spectral_ct/bin/python
 - gt_code_path: /data/yjh/storm-analysis-master_sandbox/storm_code.py
   name: storm-analysis-master
   python_path: /data/yjh/storm_env/bin/python
 - gt_code_path: /data/yjh/structured-light-python-main_sandbox/structured_light_code.py
   name: structured-light-python-main
   python_path: /data/yjh/structured_light_env/bin/python
 - gt_code_path: /data/yjh/svmbir-master_sandbox/svmbir_code.py
   name: svmbir-master
   python_path: python
 - gt_code_path: /data/yjh/tomopy-master_sandbox/tomopy_code.py
   name: tomopy-master
   python_path: python
 - gt_code_path: /data/yjh/us-beamform-linarray-master/us_beamforming.py
   name: us-beamform-linarray-master
   python_path: /usr/local/anaconda3/bin/python
 - gt_code_path: /data/yjh/nirfaster-FF-main_2_sandbox/nirfaster_code.py
   name: nirfaster-FF-main_2
   python_path: /usr/local/anaconda3/bin/python